name: niskine-proc
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipympl
  - ipdb
  - black
  - ipykernel
  - ipython
  - jupyter
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - matplotlib
  - numpy
  - pandas
  - pytest
  - scipy
  - xarray
  - pip
  - netcdf4
  - pip:
    - jupytext
    - pyrsktools
    - "-e /Users/gunnar/Projects/python/gvpy"
    - "-e /Users/gunnar/Projects/python/rbrmoored"
