name: niskine-proc
channels:
- conda-forge
dependencies:
- python=3.10
- mercurial=6.0.3
- matplotlib=3.5.1
- numpy=1.22.3
- pandas=1.4.2
- scipy=1.8.0
- xarray=2022.3.0
- dask=2022.4.1
- netcdf4=1.5.8
- requests=2.27.1
- statsmodels=0.13.2
- cartopy=0.20.2
- jupytext=1.13.8
- gsw=3.4.0
- pip
- pip:
  - tqdm==4.64.0
  - pyrsktools==0.1.8
  - seabird==0.11.5
  - hg+https://currents.soest.hawaii.edu/hgstage/pycurrents@333d57320873
  - git+https://github.com/gunnarvoet/gvpy@5d29e5ecd85d08718a7ef4e9ee43ec07b20839e3
  - git+https://github.com/gunnarvoet/rbrmoored@0c04fbb44ba2a74f03968466e65e9298795900c1
  - git+https://github.com/gunnarvoet/sbemoored@95d77cbe50b6b588d2ceccae8754a1e306b82594
  - git+https://github.com/gunnarvoet/gadcp@cb887fb42e3e5f05e71d7d75f336bfa2bbd800b2
