# This file is excluded from being tracked in git by running
# `git update-index --assume-unchanged environment.yml`
# on the command line. This can be undone with
# `git update-index --no-assume-unchanged environment.yml`
name: niskine-proc
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - pandas
  - scipy
  - xarray
  - dask
  - netcdf4
  - requests
  - statsmodels
  - cartopy
  - pip
  - pip:
    - pyrsktools
    - "-e git+https://github.com/gunnarvoet/gvpy#egg=gvpy"
    - "-e git+https://github.com/gunnarvoet/rbrmoored#egg=rbrmoored"
    - "-e git+https://github.com/gunnarvoet/sbemoored#egg=sbemoored"
    - "-e git+https://github.com/gunnarvoet/gadcp#egg=gadcp"
    # - "-e /Users/gunnar/Projects/python/gvpy"
    # - "-e /Users/gunnar/Projects/python/gadcp"
    # - "-e /Users/gunnar/Projects/python/rbrmoored"
    # - "-e /Users/gunnar/Projects/python/sbemoored"
