# This file is excluded from being tracked in git by running
# `git update-index --assume-unchanged environment.yml`
# on the command line. This can be undone with
# `git update-index --no-assume-unchanged environment.yml`
name: niskine-proc
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipympl
  - ipdb
  - black
  - ipykernel
  - ipython
  - jupyter
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - matplotlib
  - numpy
  - pandas
  - pytest
  - scipy
  - xarray
  - pip
  - netcdf4
  - pip:
    - jupytext
    - pyrsktools
    - watchmagic
    - "-e git+https://github.com/gunnarvoet/gvpy#egg=gvpy"
    - "-e git+https://github.com/gunnarvoet/rbrmoored#egg=rbrmoored"
    - "-e git+https://github.com/gunnarvoet/sbemoored#egg=sbemoored"
